name: Deploy

permissions:
  contents: write

on:
  release:
    types:
      - released  
  
jobs:
  deploy_linux:
    name: Deploy Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set version environment variable
      run: echo "MOXPP_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 
    - name: MoxPP Init
      run: ./mox.sh init
    - name: MoxPP Build
      run: ./mox.sh build
    - name: MoxPP Deploy
      run: ./mox.sh deploy
    - name: Upload artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: deploy/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  deploy_maxos:
    name: Deploy MacOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set version environment variable
      run: echo "MOXPP_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
    - name: Ensure Xcode CLI Tools
      run: |
        xcode-select --install || true
        sudo xcodebuild -license accept || true
    - name: Update Homebrew and build Tools
      run: |
        brew update
        brew install cmake ninja || true
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: MoxPP Init
      run: ./mox.sh init
    - name: MoxPP Build
      run: ./mox.sh build
    - name: MoxPP Deploy
      run: ./mox.sh deploy
    - name: Upload artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: deploy/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

  deploy_windows:
    name: Deploy Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set version environment variable
      shell: pwsh
      run: echo "MOXPP_VERSION=${{ github.event.release.tag_name }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 
    - name: MoxPP Init
      run: ./mox.bat init
    - name: MoxPP Build
      run: ./mox.bat build
    - name: MoxPP Deploy
      run: ./mox.bat deploy
    - name: Upload artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: deploy/*.*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    